mapinskhu/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static
import classApp.views, feedbackApp.views, baseApp.views

urlpatterns = [
    path('skhu21it4/', admin.site.urls),

    path('', baseApp.views.index, name='index'),
    path('introduce/', baseApp.views.introduce, name='introduce'),
    path('search/', baseApp.views.search, name = 'search'),
    
    path('dormitory/', classApp.views.dormitory, name='dormitory'),
    path('gdin_gwan/', classApp.views.gdin_gwan, name='gdin_gwan'),
    path('im_gwan/', classApp.views.im_gwan, name='im_gwan'),
    path('jg_gwan/', classApp.views.jg_gwan, name='jg_gwan'),
    path('library/', classApp.views.library, name='library'),
    path('mgell_gwan/', classApp.views.mgell_gwan, name='mgell_gwan'),
    path('nn_gwan/', classApp.views.nn_gwan, name='nn_gwan'),
    path('pb_hall/', classApp.views.pb_hall, name='pb_hall'),
    path('sbdr_school/', classApp.views.sbdr_school, name='sbdr_school'),
    path('scn_gwan/', classApp.views.scn_gwan, name='scn_gwan'),
    path('sy_gwan/', classApp.views.sy_gwan, name='sy_gwan'),
    path('wd_gwan/', classApp.views.wd_gwan, name='wd_gwan'),
    path('classroom/<str:room>/', classApp.views.classroom, name='classroom'),

    path('feedback/', feedbackApp.views.feedback, name='feedback'),
    path('feedback_cp/', feedbackApp.views.feedback_cp, name='feedback_cp'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedbackApp/models.py
from django.db import models


class Feedback(models.Model):
    feedback_date = models.DateTimeField(auto_now_add=True)
    feedback_content = models.TextField(default = "글을 작성해주세요.")
 
    def __str__(self):
        return self.feedback_content[:10]

feedbackApp/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['feedback_content']

        widgets = {
            'feedback_content': forms.Textarea(attrs={'placeholder': 'Feedback Here'}),
        } 

feedbackApp/views.py
from django.shortcuts import render, redirect
from .models import Feedback
from .forms import FeedbackForm


def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('feedback_cp')
        return redirect('feedback')
    else:
        form = FeedbackForm()
        return render(request, 'feedback.html', {'feedback_form':form})

def feedback_cp(request):
    return render(request, 'feedback_cp.html')

feedbackApp/templates/feedback.html
<!-- 피드백 페이지 -->
{% extends 'base.html' %}
{% load static %}
{% block title %} FeedBack {% endblock %}

{% block content %}

<form method = "POST">
    {% csrf_token %} 
    <div class="feedback-container">
      <div claass="fb-wrap">
        <div class="fd-head">
          <h1 style="font-size: 3rem"> 🌍 피드백 🌍 </h1>
          <h2 style="font-size: 1.2rem"> 작은 피드백은 개발에 큰 도움이 됩니다. 감사합니다!</h2>
        </div>
        <div class="fdform-wrap">
          <div class="inputform">
            <input type="text" name="user_id" maxlength="50" required id="id_user_id">
            <label for="id_user_id ">이름</label>
          </div>
          <div class="inputform">
            <input type="text" name="user_phonenum" maxlength="100" required id="id_user_phonenum" style="margin-bottom: 0;">
            <label for="id_user_id ">전화번호</label>
            <span style="margin-bottom: 30px; color: gray;">(ex. 01012341234)</span>
          </div>
          <div class="inputform">
            <textarea name="feedback_content" cols="40" rows="10" required id="id_feedback_content"></textarea>
            <label for="id_user_id ">피드백 할 내용</label>
          </div>
            <div class="smbutton">
              <a href="{% url 'index' %}">취소</a>
              <button type="submit">제출</button>
            </div>
        </div>

      </div>
    </div>

</form>


{% endblock %}

feedbackApp/templates/feedback_cp.html
<!-- 피드백 페이지 -->
{% extends 'base.html' %}
{% load static %}
{% block title %} FeedBack {% endblock %}

{% block content %}

<div class="feedback-container">
  <div class="fb-wrap" style="margin-top: 15rem;">
    <div class="fd-head">
        <h1> 🌍 소중한 의견 감사합니다! 🌍 </h1>
      </div>
    
      <div class="smbutton">
        <a href="{% url 'index' %}">홈으로</a>
      </div>
  </div>
</div>



{% endblock %}